// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20230501060218_Initial3")]
    partial class Initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<int?>("Rooms")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This luxury resort is the perfect destination for travelers seeking an indulgent and rejuvenating vacation experience. Nestled in a picturesque setting, the resort offers world-class amenities and services, including a spa, fitness center, and gourmet dining options. Guests can unwind in the comfortable and elegantly furnished rooms, which feature stunning views of the surrounding landscape. Whether you're looking for a romantic getaway or a family vacation, this resort has something for everyone.",
                            ImageUrl = "https://media.istockphoto.com/id/104731717/photo/luxury-resort.jpg?s=612x612&w=0&k=20&c=cODMSPbYyrn1FHake1xYz9M8r15iOfGz9Aosy9Db7mI=",
                            Location = "Bali, Indonesia",
                            Name = "Luxury Resort",
                            Phone = "01 797 678",
                            Ranking = 4,
                            Rooms = 200
                        },
                        new
                        {
                            Id = 2,
                            Description = "The St. Regis Dubai is a true gem of the Middle East, offering guests an unparalleled level of luxury and sophistication. Boasting an impressive array of amenities and services, this hotel is the perfect choice for discerning travelers seeking an unforgettable experience. From the stunning architecture to the exquisite interior design, every aspect of this hotel exudes elegance and refinement. Whether you're indulging in a gourmet meal at one of the hotel's restaurants or lounging by the pool, you're sure to feel pampered and relaxed.",
                            ImageUrl = "https://samchui.com/wp-content/uploads/2018/07/St-Regis-Dubai-Luxury-Hotel-in-Dubai-Exterior-Shot.jpg",
                            Location = "Dubai, UAE",
                            Name = "St. Regis Dubai",
                            Phone = "01 035 538",
                            Ranking = 5,
                            Rooms = 150
                        },
                        new
                        {
                            Id = 3,
                            Description = "This chic and modern hotel offers a refreshing take on traditional hospitality, blending contemporary design with impeccable service. With its prime location and extensive range of amenities, the hotel is the ideal choice for travelers seeking convenience and comfort. From the stylishly appointed rooms to the well-equipped fitness center, every aspect of this hotel is designed with the guest's comfort in mind. Whether you're in town for business or leisure, this hotel offers a perfect home away from home.",
                            ImageUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/106257638.jpg?k=4dd13a3f0f19081704cd50ee377462f2d13ea0662e577576e98bedc711005334&o=&hp=1",
                            Location = "Paris, France",
                            Name = "Hotel Continental",
                            Phone = "01 004 278",
                            Ranking = 3,
                            Rooms = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
