// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20230430213931_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<int?>("Rooms")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A luxurious resort with world-class amenities.",
                            ImageUrl = "https://media.istockphoto.com/id/104731717/photo/luxury-resort.jpg?s=612x612&w=0&k=20&c=cODMSPbYyrn1FHake1xYz9M8r15iOfGz9Aosy9Db7mI=",
                            Location = "Bali, Indonesia",
                            Name = "Luxury Resort",
                            Ranking = 4,
                            Rooms = 200
                        },
                        new
                        {
                            Id = 2,
                            Description = "A luxurious hotel with stunning views of Dubai.",
                            ImageUrl = "https://samchui.com/wp-content/uploads/2018/07/St-Regis-Dubai-Luxury-Hotel-in-Dubai-Exterior-Shot.jpg",
                            Location = "Dubai, UAE",
                            Name = "St. Regis Dubai",
                            Ranking = 5,
                            Rooms = 150
                        },
                        new
                        {
                            Id = 3,
                            Description = "A cozy hotel with great service and comfortable rooms.",
                            ImageUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/106257638.jpg?k=4dd13a3f0f19081704cd50ee377462f2d13ea0662e577576e98bedc711005334&o=&hp=1",
                            Location = "Paris, France",
                            Name = "Hotel Continental",
                            Ranking = 3,
                            Rooms = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
